### ISSUE TITLE
‘’https://github.com/davidiommi/3D_Prostate_segmentation_pytorch ‘’The link cannot be opened.

### ISSUE THREAD

**Issue by pangda72** [davidiommi/Pytorch-Unet3D-single_channel#2]
Hi,davidiommi

Thank you for sharing your code,When I want to open the following link:‘’https://github.com/davidiommi/3D_Prostate_segmentation_pytorch ‘’,it was found to be ineffective.I didn't find this repository on your home page.Could you please share it with me again? or could you please  send it to my email address:  Sun2818113235@163.com.
Looking forward to your reply!Thank you very much!
Good Luck to you!

**Comment by pangda72** [comment]
> Hi,davidiommi
> 
> Thank you for sharing your code,When I want to open the following link:‘’https://github.com/davidiommi/3D_Prostate_segmentation_pytorch ‘’,it was found to be ineffective.I didn't find this repository on your home page.Could you please share it with me again? or could you please send it to my email address: [Sun2818113235@163.com](mailto:Sun2818113235@163.com).
> Looking forward to your reply!Thank you very much!
> Good Luck to you!



> Hi,davidiommi
> 
> Thank you for sharing your code,When I want to open the following link:‘’https://github.com/davidiommi/3D_Prostate_segmentation_pytorch ‘’,it was found to be ineffective.I didn't find this repository on your home page.Could you please share it with me again? or could you please send it to my email address: [Sun2818113235@163.com](mailto:Sun2818113235@163.com).
> Looking forward to your reply!Thank you very much!
> Good Luck to you!

**Comment by davidiommi** [comment]
Dear pangda72,

the repository is now public.

**Comment by pangda72** [comment]
> Dear pangda72,
> 
> the repository is now public.

Thank you for your help to me.At the same time, thank you for your timely reply. I am very happy.Hope you have a good day!
