### ISSUE TITLE
 when i run ''check_resolution.py''  and "check_loader_patches.py"，I got a problem： Execute() takes 2 positional arguments but 10 were given

### ISSUE THREAD

**Issue by pangda72** [davidiommi/Pytorch-Unet3D-single_channel#3]
Dear David lommi

 when i run ''check_resolution.py''  and "check_loader_patches.py"，I met a problem：
#=====================================================================#
Traceback (most recent call last):
  File "C:/Users/lenovo/Desktop/3D UNet Pytorch/check_resolution.py", line 19, in <module>
    a = resample_sitk_image(a, spacing=args.new_resolution, interpolator='linear')
  File "C:\Users\lenovo\Desktop\3D UNet Pytorch\NiftiDataset.py", line 177, in resample_sitk_image
    orig_pixelid)
TypeError: Execute() takes 2 positional arguments but 10 were given
Process finished with exit code 1
#======================================================================#
The data set format is based on the 'read  me' you gave,I don't know how to how to deal with this problem.Could you please help me ?Looking forward to your reply!Thank you very much!

**Comment by davidiommi** [comment]
I think is the version of simpleITK.

This one should work: simpleITK==1.2.4.

Btw this is an old repository that I am not updating, I am using SALMON on my page, but it's basically written with MONAI library (you can find it on github).

If you need just the inference to segment the prostate, I can upload my last version and you can use that.

**Comment by pangda72** [comment]
> I think is the version of simpleITK.
> 
> This one should work: simpleITK==1.2.4.
> 
> Btw this is an old repository that I am not updating, I am using SALMON on my page, but it's basically written with MONAI library (you can find it on github).
> 
> If you need just the inference to segment the prostate, I can upload my last version and you can use that.

Thank you for your reply. I may not be familiar with the MONAI library ,so the SALMON on you page, but which is basically written with MONAI library  could be difficult to me.I feel very sorry. I want to refer to the segmentation of the prostatet .so I'm looking forward to the latest version that you upload.I appreciate your help.

**Comment by pangda72** [comment]
> > I think is the version of simpleITK.
> > This one should work: simpleITK==1.2.4.
> > Btw this is an old repository that I am not updating, I am using SALMON on my page, but it's basically written with MONAI library (you can find it on github).
> > If you need just the inference to segment the prostate, I can upload my last version and you can use that.
> 
> Thank you for your reply. I may not be familiar with the MONAI library ,so the SALMON on you page, but which is basically written with MONAI library could be difficult to me.I feel very sorry. I want to refer to the segmentation of the prostatet .so I'm looking forward to the latest version that you upload.I appreciate your help.

Dear davidiommi

I only find a "3D_Prostate_segmentation_pytorch"in you page.Is this the last version you upload on prostate  segmentation?
If not,could you share with me about the last version,which is  a great help to me.Looking forward to your reply,thank you very very much!

**Comment by davidiommi** [comment]
It's not the last version. I will upload it this week.

You can try anyway 3D_Prostate_segmentation_pytorch and see if it works.

I ask you if you have a gpu or only cpu to run the inference.

**Comment by pangda72** [comment]
> It's not the last version. I will upload it this week.
> 
> You can try anyway 3D_Prostate_segmentation_pytorch and see if it works.
> 
> I ask you if you have a gpu or only cpu to run the inference.

I'll do my best to run "3D_Prostate_segmentation_pytorch"  this week!  And  I have a GPU  to run the inference.Thank you very much. I feel very lucky.

**Comment by davidiommi** [comment]
I shared with you a folder where you can find what you need.

Check installation commands and modify the argsparse in the .py file to give the input data

**Comment by pangda72** [comment]
> I shared with you a folder where you can find what you need.
> 
> Check installation commands and modify the argsparse in the .py file to give the input data.
> 
> Once you download it tell me because I have to delete it.

Dear davidiommi
I am very happy to receive your reply.But i feel very sorry ,I've been looking for the folder you shared with me ,but I couldn't find it in you page!Could you teach me ?

**Comment by davidiommi** [comment]
I sent you an invitation for a private folder. Check your mail

**Comment by pangda72** [comment]
> I sent you an invitation for a private folder. Check your mail

so that's it.Dear davidiommi, I have download it .you can delete it now.As far as I am concerned, you have given me a great help.I feel very happy and lucky.thank you!you've  been very helpful.You told me to run "3D_Prostate_segmentation_pytorch"   earlier,I have run it successfully, but the results are not very good, I am trying to modify it.In a word, thank you very much!Hope you have a good day!
Best wishes!

**Comment by davidiommi** [comment]
Keep the settings like that (resolution and patch size), because the model is optimized for those ones. You will get as output the same resolution and size of your original image anyway. Just give the image as input.

**Comment by pangda72** [comment]
Thank you for your advice,which could be a greart help to me,I will modify it as follows.Hope we can keep in touch often!

**Comment by pangda72** [comment]
> Keep the settings like that (resolution and patch size), because the model is optimized for those ones. You will get as output the same resolution and size of your original image anyway. Just give the image as input.

Thank you for your advice,which could be a greart help to me,I will modify it as follows.Hope we can keep in touch often!
